### ISSUE TITLE
NFT Marketplace: update collections

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [notional-labs/anone#102]
# I. Task description
Collection fields:
name, symbol, admin, description, image, external_link, royaly_info

changable fields:
1. description: mô tả về collections
2. image: image url
3. external_link: link đi kèm
4. royalty_info: thông tin royalty của smart contract {royalPaymentAddress and royalShareFee)

an UI to update collection fields

# II. Task timeline
09/05 - 15/05

# IV. Task goals 
goals that this task needs to achieve

- [x]  functioning UI

**Comment by chinhnotional** [comment]
We don't update name and symbol of collection to maintain the stability feature of a collection NFT. Only change fields: description, image, external_link, royalty_info

**Comment by sontrinh16** [comment]
has finish runable UI, demo will be provide on the next meet
