### ISSUE TITLE
PHASE 2: add ethermint to anone

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [notional-labs/anone#11]
discussion goes here:

[ethermint implementation](https://github.com/notional-labs/anone/pull/10)

- [x] missing JSON-RPC configuration in app.toml. The hell? done
- [x] invalid chain ID?
- [x] metamask does not display amount?
- [x] testing send
- [ ] any more test?

**Comment by nghuyenthevinh2000** [comment]
so far, I have changed to app, rootCmd, and encoding.

**Comment by nghuyenthevinh2000** [comment]
change to root.go in spm to include configuration for JSON RPC in app.toml:

**Comment by nghuyenthevinh2000** [comment]
change to genesis-gen-accounts to add Eth_Secp256k1 address to genesis.json

**Comment by nghuyenthevinh2000** [comment]
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x471C5E8e694AfB1b2212428FD760265A28124cb0", "latest"],"id":1}' -H "Content-Type: application/json" http://localhost:8545

**Comment by nghuyenthevinh2000** [comment]
FFFFFFFFFFFUUUUUUUUUUUUCCCCCCCCCCCCKKKKKKKKKKKKK, finally

**Comment by nghuyenthevinh2000** [comment]
evm is mainly resposible for handling all JSON-RPC call:

1. rpc/etherum/namespaces/eth/api.go
2. x/evm/keeper/grpc_query.go
3. x/evm/keeper/statedb.go

The above order is how a JSON - RPC is handled.

**Comment by nghuyenthevinh2000** [comment]
genesis.json provides chain params (field "app_state") which will be passed to InitGenesis(). That params will then be used by evm keeper to configure its own configuration

**Comment by nghuyenthevinh2000** [comment]
change to ethermint crypto/hd/algorithm.go will allow eth_secp256k1 algorithm be used for Metamask and secp256k1 be used for Cosmos wallet.

**Comment by nghuyenthevinh2000** [comment]
This one cannot be added for now because it is conflicting with air drop stuffs. The addr of airdrop like Blurt follows HDPATH of cointype 118 while default cointype of etherming is 60. I must choose one because there can only be one coinType on keplr. Thus, it has to be default 118.

The possibility of integrating ethermint is bad for all types of cosmos chain until another solution is found due to the problem above.

**Comment by nghuyenthevinh2000** [comment]
anoned keys add temp --recover --algo secp256k1 --coin-type 118 can still generate correct seck256k1 addr

**Comment by nghuyenthevinh2000** [comment]
sending functionalities does work. I test in Metamask and it does send from 0x addr to another 0x addr. 

In Metamask, it is not possible to send to another dig1 acc.

**Comment by faddat** [comment]
.....this shall be an evm chain?

Oh, my

**Comment by nghuyenthevinh2000** [comment]
I will say that decision is still uncertain.

**Comment by nghuyenthevinh2000** [comment]
ethermint will be changed to Gravity Bridge instead
