### ISSUE TITLE
Setup Testnet - 1 and validators

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [notional-labs/anone#2]
Goal: work with test - net validators to set up test - net 1

Precondition: 

- [x] Active Discord server with few validators in it
- [x] Modification to chain: IBC (still working on this with Khanh to see if I miss anything)
- [x] genesis.json set up in code base
- [x] IPFS for storing genesis.json 
- [x] wait for consensus state reached

**Comment by nghuyenthevinh2000** [comment]
the testnet faces such a stupid bugs about not reaching consensus state even after 66% consensus progress

**Comment by mgialong215** [comment]
Testnet's running but need the faucet to be done before publishing.
