### ISSUE TITLE
Cosmos SDK Upstream Action

### ISSUE THREAD

**Issue by faddat** [notional-labs/anone#43]
When we began this work, it was not clear when/if/how native NFTs would exist in the cosmos-sdk.

We now know the answer, they're landing in cosmos-sdk v0.46.0, which we're using for Craft Economy. 

Today I updated starport to v0.45.0

https://github.com/tendermint/starport/pull/2039

This means that it can now scaffold Cosmos-SDK v0.45.0 chains, but this version isn't super-different from v0.44.x-- mainly some performance enhancements that are centered around wasm & the upcoming release of evmos. 

So, we're faced with a choice here:

1) We launch with Cosmos-SDK v0.45.0 and we do NFTs using CosmWasm like Stargaze.zone

OR

2) We launch with Cosmos-SDK v0.46.0 and we do native NFTs, with or without CosmWasm

what do you think?

The key difference will likely be timeline.  Also, in the event that we ship v0.46.0, we will need to figure out weather or not we should support CosmWasm.

**Comment by nghuyenthevinh2000** [comment]
even if v0.46.0 is launched, it will need sometimes to achieve stable version. v0.45.0 with CosmWasm is still solid choice.

**Comment by faddat** [comment]
I'm going to delegate the decision to you guys, so, if ya want 45, go for it -- ditto 46 :)
