### ISSUE TITLE
PHASE 2: Add CosmWasm NFT module to anone

### ISSUE THREAD

**Issue by whatzaruckus** [notional-labs/anone#6]
[CosmWasm NFT](https://github.com/CosmWasm/cw-nfts)

- [x] basic experiment on how to write CosmWasm. Deliverables: functioning CosmWasm
- [x] basic experiement on how to implement CosmWasm NFT. Deliverables: functioning contract to mint 
- [x] deploy contract to testnet - 1.0.3

--------------------------------------------

- [x] testing: same token-id must return false
- [x] any more test?

https://github.com/notional-labs/anone/tree/wasm-import

**Comment by nguyenvuong1122000** [comment]
I imported wasm to anone in branch : https://github.com/notional-labs/anone/tree/wasm-import

**Comment by nghuyenthevinh2000** [comment]
finish scaffold a basic structure of SM. Moving on to coding more functionalities of NFT.

**Comment by nghuyenthevinh2000** [comment]
basic NFT smart contract is written and deployed. Resolving deploying problems.

**Comment by nghuyenthevinh2000** [comment]
1. Start a testnet - 1.0.3 node
2. store contract to chain: anoned tx wasm store --help
3. instantiate contract: anoned tx wasm instantiate --help
4. guide good to read on how to deploy: https://github.com/notional-labs/oracle-ibc
5. template code on how to write a contract: https://github.com/notional-labs/cw-nfts/tree/main/contracts
6. try to mint --> fail --> debug --> solution

**Comment by nghuyenthevinh2000** [comment]
done
