### ISSUE TITLE
API and RPC node address

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [notional-labs/anone#74]
There are two types of Anone nodes:

1. Attestation site's Node:

- RPC address: http://49.12.213.105:2221
- API address: http://49.12.213.105:1317

2. Testnet Node:

- RPC address: http://65.108.128.139:2281
- API address: http://65.108.128.139:2284

**Comment by mgialong215** [comment]
Edited, done.

**Comment by nghuyenthevinh2000** [comment]
I cannot access http://65.108.128.139:2284

**Comment by mgialong215** [comment]
fixed
