### ISSUE TITLE
Minting An1 on BSC to launch on Polygon network

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [notional-labs/anone#82]
# I. Task description
Minting vAN1 on Polygon to this address: 0x4C9658E77D53D0e9B190acec4FEDC60D2875fd94

# II. Task timeline
Not yet specified

# III. Task deliverables
vAN1 on Polygon

# IV. Task goals 

- [x]  mint 4millions vAN1 on Polygon

**Comment by hieuvubk** [comment]
Deployed AN1 mintable ERC20 on bsctestnet

**Comment by nghuyenthevinh2000** [comment]
@hieuvubk 
can you give me the link to that smart contract?

**Comment by hieuvubk** [comment]
> @hieuvubk can you give me the link to that smart contract?

https://testnet.bscscan.com/address/0x165e667e418d7ad79D073BfcfA5C2FcE0D2F0565
Contract verified, u can test function on explorer.
Need use this private key to mint/burn token: c714e6974c75d6919d429cc9f55ee22aaa7770c1ba95ad9c983f16c27ee92d62

**Comment by nghuyenthevinh2000** [comment]
@hieuvubk 
I have updated the amount to mint (4 millions an1). Please mint those amount on mainnet

**Comment by nghuyenthevinh2000** [comment]
task updated, please have a look again @hieuvubk
