### ISSUE TITLE
New NFT smart contract

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [notional-labs/anone#88]
# I. Task description
A new NFT smart contract

@chinhnotional 
The new contract for NFT that you have written. Please post images of cli interacting with your smart Contract v2 to here so I can know what it will do. 

# II. Task timeline
Specify timeline if exists

# III. Task deliverables
What deliverables do this task need to deliver?

# IV. Task goals 
goals that this task needs to achieve

- [x]  Build sh files to test contract

**Comment by chinhnotional** [comment]
Currently, I have written a set of 1 package called an-std (for the purpose of providing a function to handle burning and distributing collection creation fees) and 3 contracts including anone-minter (for the purpose of creating collections for artists). , an721 (which is the standard for NFT collection) and anone-nft-marketplace (which is a contract for NFT trading: transfer NFT cw721 to the buyer and transfer cw20 token AN1 to the seller - this contract is not running properly logic yet. ). The old contract anone-cw721 is still used for the sole purpose of minting 1 nft to the function caller, for demo purposes only, and will soon be replaced by a production version.
I'll be writing a script soon to help you understand how contracts work.

**Comment by chinhnotional** [comment]
Deploy anone-nft-marketplace contract
![Uploading Deploy_anone_nft_markeplace_contract.png…]()

**Comment by chinhnotional** [comment]
Deploy anone-nft-marketplace contract
![Deploy_anone_nft_markeplace_contract](https://user-images.githubusercontent.com/100383075/161189508-2137aae8-9d25-440f-ac92-3a3c52222a1e.png)

**Comment by chinhnotional** [comment]
Create sale for NFT with token_id is 2 and nft collection contract is: one1nc5tatafv6eyq7llkr2gv50ff9e22mnf70qgjlv737ktmt4eswrq9jdqcm
from owner: one1sgdktd56d6ku5ud00dlss0r27u6rx8gq2080fm
to nft-marketplace contract: one19vrjp7fll6a729v464wlxr8a2xqhcddc0e5f0gxkv4fcyl8n23us4mr5jv
Check tx in here: https://test-anone.zenscan.io/transaction.php?hash=339E98BC218EC4A41808A202F241D3EA918F7D9FACE031D7AA7AA9161308D073
![Create_sale](https://user-images.githubusercontent.com/100383075/161189850-abcc317c-5de1-433a-b8ed-5b2a07b8d879.png)

**Comment by chinhnotional** [comment]
@nghuyenthevinh2000 
After create sale, that NFT will have list_price is 500 MAGE (because I use mageNFT cw20 token for test)

**Comment by chinhnotional** [comment]
After create sale, owner of that NFT can cancel sale, and that NFT will go back to owner address and no longer available in marketplace.
Check tx in here: https://test-anone.zenscan.io/transaction.php?hash=44B558F644B832878B5D6B721B32D4712C5F3E33E74E7C309F597EBFDE3271C5
![cancel_sale](https://user-images.githubusercontent.com/100383075/161191553-190595b4-ccfb-4424-a120-ded9695878c5.png)

**Comment by chinhnotional** [comment]
Buy nft function is ok.
Buy an NFT with token_id is 4 and offering is 10. Buyer is one1sgdktd56d6ku5ud00dlss0r27u6rx8gq2080fm:
![Screenshot from 2022-04-05 04-00-45](https://user-images.githubusercontent.com/100383075/161631576-bd1434e0-eff5-415d-a9d8-02bf69e583f5.png)
After buy, this nft is transfered from nft-marketplace address to buyer address:
![Screenshot from 2022-04-05 04-00-29](https://user-images.githubusercontent.com/100383075/161631777-42b10abd-24be-4b9f-8477-bca45e691230.png)
