### ISSUE TITLE
Claim Module

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [notional-labs/anone#92]
# I. Task description
a claim module so as to incentivize users to interact with Anone for airdrop

the following missions: (total 100%)

- [x] initial claim (10%)
- [x] stake (20%)
- [x] vote (20%)
- [x] buy a shoe NFT (50%)

# II. Task timeline
Specify timeline if exists

# III. Task deliverables
What deliverables do this task need to deliver?

# IV. Task goals 
goals that this task needs to achieve

- [x]  functioning claims module
- [x] JS script for querying claims (https://github.com/notional-labs/anonejs)

**Comment by nghuyenthevinh2000** [comment]
claims module layout with no bugs is done.
1. go test is ok
2. doing more test on - chain.
3. need to change missions.

code is living on branch: [claims-module](https://github.com/notional-labs/anone/tree/claims-module)

**Comment by hieuvubk** [comment]
claims on local node ok

**Comment by nghuyenthevinh2000** [comment]
Need to confirm claim reward ratio

**Comment by hieuvubk** [comment]
Currently claim reward ratio same as described above. Can close issue

**Comment by nghuyenthevinh2000** [comment]
@hieuvubk 
1. ông viết điều muốn bàn luận vào đây
2. cần phức tạp hơn nữa thì setup meet

**Comment by hieuvubk** [comment]
MintNFT mission: 

- Sau khi user mint nft, cần gửi một message ClaimFor tới module Claim ( tham khảo tại [stargaze-contract-claim](https://github.com/public-awesome/stargaze-contracts/blob/main/contracts/claim/src/contract.rs)
- message này sau đó sẽ được xử lý tại [msg_server_claim_for](https://github.com/notional-labs/anone/blob/claims-module/x/claims/keeper/msg_server_claim_for.go)
