### ISSUE TITLE
anoned balance issue

### ISSUE THREAD

**Issue by papanomad535** [notional-labs/anone#93]
anoned q bank balances one1g2467695x0yacssvs8q6zc04ek8dg42lkmgkg2
balances:
- amount: "24450"
  denom: uan1
pagination:
  next_key: null
  total: "0"

anoned tx staking delegate onevaloper1g2467695x0yacssvs8q6zc04ek8dg42lhqtkpx 23000uan1 --from stakr --fees 200uan1

{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgDelegate","delegator_address":"one1g2467695x0yacssvs8q6zc04ek8dg42lkmgkg2","validator_address":"onevaloper1g2467695x0yacssvs8q6zc04ek8dg42lhqtkpx","amount":{"denom":"uan1","amount":"23000"}}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[{"denom":"uan1","amount":"200"}],"gas_limit":"200000","payer":"","granter":""}},"signatures":[]}

confirm transaction before signing and broadcasting [y/N]: y
code: 0
codespace: ""
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: '[]'
timestamp: ""
tx: null
txhash: A7FD66359D02EE4B01210D7592AB49593EDA4B1B543C20D8254B7661B5CE73DB

anoned q tx A7FD66359D02EE4B01210D7592AB49593EDA4B1B543C20D8254B7661B5CE73DB
code: 0
codespace: ""
data: 0A250A232F636F736D6F732E7374616B696E672E763162657461312E4D736744656C6567617465
events:
- attributes:
  - index: true
    key: c3BlbmRlcg==
    value: b25lMWcyNDY3Njk1eDB5YWNzc3ZzOHE2emMwNGVrOGRnNDJsa21na2cy
  - index: true
    key: YW1vdW50
    value: MjAwdWFuMQ==
  type: coin_spent
- attributes:
  - index: true
    key: cmVjZWl2ZXI=
    value: b25lMTd4cGZ2YWttMmFtZzk2MnlsczZmODR6M2tlbGw4YzVsbGNkcHF6
  - index: true
    key: YW1vdW50
    value: MjAwdWFuMQ==
  type: coin_received
- attributes:
  - index: true
    key: cmVjaXBpZW50
    value: b25lMTd4cGZ2YWttMmFtZzk2MnlsczZmODR6M2tlbGw4YzVsbGNkcHF6
  - index: true
    key: c2VuZGVy
    value: b25lMWcyNDY3Njk1eDB5YWNzc3ZzOHE2emMwNGVrOGRnNDJsa21na2cy
  - index: true
    key: YW1vdW50
    value: MjAwdWFuMQ==
  type: transfer
- attributes:
  - index: true
    key: c2VuZGVy
    value: b25lMWcyNDY3Njk1eDB5YWNzc3ZzOHE2emMwNGVrOGRnNDJsa21na2cy
  type: message
- attributes:
  - index: true
    key: ZmVl
    value: MjAwdWFuMQ==
  type: tx
- attributes:
  - index: true
    key: YWNjX3NlcQ==
    value: b25lMWcyNDY3Njk1eDB5YWNzc3ZzOHE2emMwNGVrOGRnNDJsa21na2cyLzE1NDk=
  type: tx
- attributes:
  - index: true
    key: c2lnbmF0dXJl
    value: SDE1NUhMZHppazI5Q3ptSWk2a05mR29iUkpBTjc1TnZuZUdGOWpIdDRGQm5VcXZQYmk4T1ZiQStUODlaMmFISHYvWTNYbENnL3VKc2ZFYmh3Yys3a1E9PQ==
  type: tx
- attributes:
  - index: true
    key: YWN0aW9u
    value: L2Nvc21vcy5zdGFraW5nLnYxYmV0YTEuTXNnRGVsZWdhdGU=
  type: message
- attributes:
  - index: true
    key: c3BlbmRlcg==
    value: b25lMWp2NjVzM2dycWY2djZqbDNkcDR0NmM5dDlyazk5Y2Q4ZzcyYXpx
  - index: true
    key: YW1vdW50
    value: MzkwODY4NjM1MnVhbjE=
  type: coin_spent
- attributes:
  - index: true
    key: cmVjZWl2ZXI=
    value: b25lMWcyNDY3Njk1eDB5YWNzc3ZzOHE2emMwNGVrOGRnNDJsa21na2cy
  - index: true
    key: YW1vdW50
    value: MzkwODY4NjM1MnVhbjE=
  type: coin_received
- attributes:
  - index: true
    key: cmVjaXBpZW50
    value: b25lMWcyNDY3Njk1eDB5YWNzc3ZzOHE2emMwNGVrOGRnNDJsa21na2cy
  - index: true
    key: c2VuZGVy
    value: b25lMWp2NjVzM2dycWY2djZqbDNkcDR0NmM5dDlyazk5Y2Q4ZzcyYXpx
  - index: true
    key: YW1vdW50
    value: MzkwODY4NjM1MnVhbjE=
  type: transfer
- attributes:
  - index: true
    key: c2VuZGVy
    value: b25lMWp2NjVzM2dycWY2djZqbDNkcDR0NmM5dDlyazk5Y2Q4ZzcyYXpx
  type: message
- attributes:
  - index: true
    key: c3BlbmRlcg==
    value: b25lMWcyNDY3Njk1eDB5YWNzc3ZzOHE2emMwNGVrOGRnNDJsa21na2cy
  - index: true
    key: YW1vdW50
    value: MjMwMDB1YW4x
  type: coin_spent
- attributes:
  - index: true
    key: cmVjZWl2ZXI=
    value: b25lMWZsNDh2c25tc2R6Y3Y4NXE1ZDJxNHo1YWpkaGE4eXUzNjY4d2pn
  - index: true
    key: YW1vdW50
    value: MjMwMDB1YW4x
  type: coin_received
- attributes:
  - index: true
    key: dmFsaWRhdG9y
    value: b25ldmFsb3BlcjFnMjQ2NzY5NXgweWFjc3N2czhxNnpjMDRlazhkZzQybGhxdGtweA==
  - index: true
    key: YW1vdW50
    value: MjMwMDB1YW4x
  - index: true
    key: bmV3X3NoYXJlcw==
    value: MjMwMDAuMDAwMDAwMDAwMDAwMDAwMDAw
  type: delegate
- attributes:
  - index: true
    key: bW9kdWxl
    value: c3Rha2luZw==
  - index: true
    key: c2VuZGVy
    value: b25lMWcyNDY3Njk1eDB5YWNzc3ZzOHE2emMwNGVrOGRnNDJsa21na2cy
  type: message
gas_used: "159520"
gas_wanted: "200000"
height: "665210"
info: ""
logs:
- events:
  - attributes:
    - key: receiver
      value: one1g2467695x0yacssvs8q6zc04ek8dg42lkmgkg2
    - key: amount
      value: 3908686352uan1
    - key: receiver
      value: one1fl48vsnmsdzcv85q5d2q4z5ajdha8yu3668wjg
    - key: amount
      value: 23000uan1
    type: coin_received
  - attributes:
    - key: spender
      value: one1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8g72azq
    - key: amount
      value: 3908686352uan1
    - key: spender
      value: one1g2467695x0yacssvs8q6zc04ek8dg42lkmgkg2
    - key: amount
      value: 23000uan1
    type: coin_spent
  - attributes:
    - key: validator
      value: onevaloper1g2467695x0yacssvs8q6zc04ek8dg42lhqtkpx
    - key: amount
      value: 23000uan1
    - key: new_shares
      value: "23000.000000000000000000"
    type: delegate
  - attributes:
    - key: action
      value: /cosmos.staking.v1beta1.MsgDelegate
    - key: sender
      value: one1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8g72azq
    - key: module
      value: staking
    - key: sender
      value: one1g2467695x0yacssvs8q6zc04ek8dg42lkmgkg2
    type: message
  - attributes:
    - key: recipient
      value: one1g2467695x0yacssvs8q6zc04ek8dg42lkmgkg2
    - key: sender
      value: one1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8g72azq
    - key: amount
      value: 3908686352uan1
    type: transfer
  log: ""
  msg_index: 0
raw_log: '[{"events":[{"type":"coin_received","attributes":[{"key":"receiver","value":"one1g2467695x0yacssvs8q6zc04ek8dg42lkmgkg2"},{"key":"amount","value":"3908686352uan1"},{"key":"receiver","value":"one1fl48vsnmsdzcv85q5d2q4z5ajdha8yu3668wjg"},{"key":"amount","value":"23000uan1"}]},{"type":"coin_spent","attributes":[{"key":"spender","value":"one1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8g72azq"},{"key":"amount","value":"3908686352uan1"},{"key":"spender","value":"one1g2467695x0yacssvs8q6zc04ek8dg42lkmgkg2"},{"key":"amount","value":"23000uan1"}]},{"type":"delegate","attributes":[{"key":"validator","value":"onevaloper1g2467695x0yacssvs8q6zc04ek8dg42lhqtkpx"},{"key":"amount","value":"23000uan1"},{"key":"new_shares","value":"23000.000000000000000000"}]},{"type":"message","attributes":[{"key":"action","value":"/cosmos.staking.v1beta1.MsgDelegate"},{"key":"sender","value":"one1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8g72azq"},{"key":"module","value":"staking"},{"key":"sender","value":"one1g2467695x0yacssvs8q6zc04ek8dg42lkmgkg2"}]},{"type":"transfer","attributes":[{"key":"recipient","value":"one1g2467695x0yacssvs8q6zc04ek8dg42lkmgkg2"},{"key":"sender","value":"one1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8g72azq"},{"key":"amount","value":"3908686352uan1"}]}]}]'
timestamp: "2022-04-06T17:02:43Z"
tx:
  '@type': /cosmos.tx.v1beta1.Tx
  auth_info:
    fee:
      amount:
      - amount: "200"
        denom: uan1
      gas_limit: "200000"
      granter: ""
      payer: ""
    signer_infos:
    - mode_info:
        single:
          mode: SIGN_MODE_DIRECT
      public_key:
        '@type': /cosmos.crypto.secp256k1.PubKey
        key: AnUdFOSgkfYePpUqAo/jGOs7YueewXstg3GX4TguZ38C
      sequence: "1549"
  body:
    extension_options: []
    memo: ""
    messages:
    - '@type': /cosmos.staking.v1beta1.MsgDelegate
      amount:
        amount: "23000"
        denom: uan1
      delegator_address: one1g2467695x0yacssvs8q6zc04ek8dg42lkmgkg2
      validator_address: onevaloper1g2467695x0yacssvs8q6zc04ek8dg42lhqtkpx
    non_critical_extension_options: []
    timeout_height: "0"
  signatures:
  - H155HLdzik29CzmIi6kNfGobRJAN75NvneGF9jHt4FBnUqvPbi8OVbA+T89Z2aHHv/Y3XlCg/uJsfEbhwc+7kQ==
txhash: A7FD66359D02EE4B01210D7592AB49593EDA4B1B543C20D8254B7661B5CE73DB

anoned q bank balances one1g2467695x0yacssvs8q6zc04ek8dg42lkmgkg2
balances:
- amount: "3908687602"
  denom: uan1
pagination:
  next_key: null
  total: "0"

**Comment by nghuyenthevinh2000** [comment]
@papanomad535 
can you tell exactly what is the problem?

**Comment by nghuyenthevinh2000** [comment]
if so, it could be network problem. Because, in the end, balance still updates to the right amount.
