### ISSUE TITLE
NFT Marketplace: create logic

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [notional-labs/anone#94]
# I. Task description
Create logic in NFT marketplace

part of: https://github.com/notional-labs/anone/issues/78

![collections_contracts_nfts_relationship drawio](https://user-images.githubusercontent.com/23058164/162962907-f6794034-2230-43e0-880d-95cf1c6318f5.png)

# II. Task timeline
11/4/2022 - 17/4/2022

- [x] meet again on 14/04/2022
- [x] meet again on 21/04/2022

# III. Task deliverables

# IV. Task goals 
goals that this task needs to achieve

- [x]  functional creating NFTs present on NFT marketplace
- [x] create collections
- [x] collections can add arbitrary number of NFTs (900 shoe1, 400 shoe2)
- [x] add arbitrary number of NFTs to existing collections

**Comment by sontrinh16** [comment]
file:///home/sontr/Pictures/Screenshot%20from%202022-04-20%2015-11-58.png

**Comment by sontrinh16** [comment]
![Screenshot from 2022-04-20 15-11-58](https://user-images.githubusercontent.com/48055119/164182557-9a987931-d086-42b7-9d71-8da5efd0e38e.png)

**Comment by nghuyenthevinh2000** [comment]
1. Phí create collections: (% go to community pool, % go to burn)
2. Phí mint NFT trong 1 collections: (% go to community pool, % go to burn, % go to minter)

**Comment by chinhnotional** [comment]
Collection info field:
name, symbol, admin, descryption, image, external_link, royaly_info
